#!/usr/bin/env node
/**
 * Writes a small deterministic sample CSV for manual smoke testing:
 *
 *   npm run sample            → sample-data/EURUSD-1m.csv
 *   npm run sample -- --bars 200000 --out big.csv
 *
 * The rows are SYNTHETIC. They exist so the import path can be exercised without
 * shipping a real dataset in the repository, and are labelled as such in the file
 * header. Never use them for research conclusions.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const argv = process.argv.slice(2);
function flag(name, fallback) {
  const i = argv.indexOf(`--${name}`);
  if (i === -1) return fallback;
  const next = argv[i + 1];
  if (next === undefined || next.startsWith('--')) return true;
  return next;
}

const bars = Math.max(1, Number(flag('bars', 5000)) || 5000);
const out = resolve(process.cwd(), String(flag('out', 'sample-data/EURUSD-1m.csv')));
const tfMinutes = Math.max(1, Number(flag('tf', 1)) || 1);
const symbol = String(flag('symbol', 'EURUSD'));
const startUtc = Date.parse(String(flag('start', '2024-01-02T00:00:00Z')));
if (Number.isNaN(startUtc)) {
  console.error('sample: --start must be an ISO date');
  process.exit(1);
}
const step = tfMinutes * 60_000;

// mulberry32: same seed, same file, every run.
let state = 0x2f6e2b1;
const rnd = () => {
  state |= 0;
  state = (state + 0x6d2b79f5) | 0;
  let t = Math.imul(state ^ (state >>> 15), 1 | state);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};

const pad = (n, w = 2) => String(n).padStart(w, '0');
const rows = [];
let price = 1.0853;
let cursor = startUtc;
let slot = 0;
while (rows.length < bars && slot < bars * 6 + 10_000) {
  slot++;
  const d = new Date(cursor);
  const wd = d.getUTCDay();
  // Mirror the FX session: closed Saturday, Sunday and after Friday 21:00 UTC.
  if (tfMinutes < 1440 && (wd === 6 || wd === 0 || (wd === 5 && d.getUTCHours() >= 21))) {
    cursor += step;
    continue;
  }
  const shock = (rnd() + rnd() + rnd() + rnd() - 2) * 0.00035;
  const drift = Math.sin(rows.length / 900) * 0.00004;
  const open = price;
  const close = Math.max(0.5, open + shock + drift);
  const wick = Math.abs(shock) * (0.6 + rnd() * 1.4) + 0.00006;
  const high = Math.max(open, close) + wick * rnd();
  const low = Math.min(open, close) - wick * rnd();
  const volume = Math.round(60 + rnd() * 240 + Math.abs(shock) * 900_000);
  rows.push(
    [
      `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}`,
      `${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}`,
      open.toFixed(5),
      high.toFixed(5),
      low.toFixed(5),
      close.toFixed(5),
      String(volume),
    ].join(','),
  );
  price = close;
  cursor += step;
}

const header = [
  `# SYNTHETIC SAMPLE — generated by scripts/gen-sample.mjs, not real market data.`,
  `# symbol=${symbol} timeframe=${tfMinutes}m bars=${rows.length} timezone=UTC`,
  'Date,Time,Open,High,Low,Close,Volume',
].join('\n');

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${header}\n${rows.join('\n')}\n`, 'utf8');
console.log(`sample: wrote ${rows.length} rows to ${out} (${(rows.length * 48 / 1024).toFixed(0)} KiB approx)`);
console.log('sample: import it from the app — it is labelled synthetic in the report.');
